# Generated by Django 3.1.7 on 2021-02-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nbaPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=150)),
                ('number', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=3)),
                ('age', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
            ],
        ),
    ]
